version: "3.9"
services:
  redis:
    image: redis:7-alpine
    container_name: fintrack-redis
    ports:
      - "6379:6379"

  auth-service:
    build: ../backend/auth-service
    container_name: fintrack-auth
    ports:
      - "8081:8080"
    depends_on:
      - redis

  transaction-service:
    build: ../backend/transaction-service
    container_name: fintrack-transaction
    ports:
      - "8082:8080"
    depends_on:
      - redis

  gateway:
    build: ../backend/gateway
    container_name: fintrack-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - transaction-service
