services:
  redis:
    image: redis:7-alpine
    container_name: fintrack-redis
    ports:
      - "6379:6379"

  auth-service:
    build:
      context: ../backend/auth-service/auth-service
      dockerfile: Dockerfile
    container_name: fintrack-auth
    ports:
      - "8081:8080"
    depends_on:
      - redis

  transaction-service:
    build:
      context: ../backend/transaction-service/transaction-service
      dockerfile: Dockerfile
    container_name: fintrack-transaction
    ports:
      - "8082:8080"
    depends_on:
      - redis

  gateway:
    build:
      context: ../backend/gateway/gateway-service
      dockerfile: Dockerfile
    container_name: fintrack-gateway
    image: infra-gateway-service
    ports:
      - "8083:8080"
    depends_on:
      - redis
