services:
  redis:
    image: redis:7-alpine
    container_name: fintrack-redis
    ports:
      - "6379:6379"

  auth-service:
    build: ../backend/auth-service/auth-service
    container_name: fintrack-auth
    ports:
      - "8081:8080"
    depends_on:
      - redis

  transaction-service:
    build: ../backend/transaction-service/transaction-service
    container_name: fintrack-transaction
    ports:
      - "8082:8080"
    depends_on:
      - redis
      - postgres

  gateway:
    build:
      context: ../backend/gateway/gateway-service
      dockerfile: Dockerfile
    container_name: fintrack-gateway
    ports:
      - "8083:8080"
    depends_on:
      - auth-service
      - transaction-service

  postgres:
    image: postgres:16-alpine
    container_name: fintrack-postgres
    environment:
      POSTGRES_DB: fintrack
      POSTGRES_USER: fintrack
      POSTGRES_PASSWORD: fintrack
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
