server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: http://fintrack-auth:8080
            predicates:
              - Path=/api/auth/**
          - id: transaction-service
            uri: http://fintrack-transaction:8080
            predicates:
              - Path=/api/transactions/**

app:
  jwt:
    secret: "super-secret-key-fintrack-1234567890"
